-- ==============================================================================
-- PARTE 12: NOVOS PRODUTOS FALTANTES (19 PRODUTOS)
-- ==============================================================================

BEGIN;

INSERT INTO public.products (
  id, hospital_id, nome, categoria, referencia, tecido, tamanhos, cores, dimensoes, detalhes, imagem_principal, imagens_detalhe, pintura, marca_cliente, nome_campo, timbrado, rastreavel, arquivado, created_at, updated_at
) VALUES (
  'f1000001-0000-4000-8000-000000000031',
  '56cd484d-914f-4d7d-9114-c8a51982e414',
  'Moletom M',
  'Moletom',
  'SB - 0031',
  'Moletom Flanelado',
  ARRAY['M']::text[],
  '[{"id":"c-azul","nome":"Azul","hex":"#223b7b"},{"id":"c-verde","nome":"Verde","hex":"#00683a"}]'::jsonb,
  '[{"id":"dim-31","titulo":"Dimensões","largura":"56 cm","altura":"68 cm","unidade":"cm"}]'::jsonb,
  '[{"id":"det-31","texto":"Punho e barra com ribana"}]'::jsonb,
  '',
  '[]'::jsonb,
  '{"cor":"","tamanho":"","localizacao":"","imagem":""}'::jsonb,
  '{"cor":"","tamanho":"","localizacao":"","imagem":""}'::jsonb,
  '{"texto":"","cor":"","tamanho":"","localizacao":""}'::jsonb,
  '{"ativo":false,"imagem":""}'::jsonb,
  '{"ativo":false,"imagem":""}'::jsonb,
  FALSE,
  now(),
  now()
) ON CONFLICT (id) DO UPDATE SET
  hospital_id = EXCLUDED.hospital_id,
  nome = EXCLUDED.nome,
  categoria = EXCLUDED.categoria,
  referencia = EXCLUDED.referencia,
  tecido = EXCLUDED.tecido,
  tamanhos = EXCLUDED.tamanhos,
  cores = EXCLUDED.cores,
  dimensoes = EXCLUDED.dimensoes,
  detalhes = EXCLUDED.detalhes,
  imagem_principal = EXCLUDED.imagem_principal,
  imagens_detalhe = EXCLUDED.imagens_detalhe,
  pintura = EXCLUDED.pintura,
  marca_cliente = EXCLUDED.marca_cliente,
  nome_campo = EXCLUDED.nome_campo,
  timbrado = EXCLUDED.timbrado,
  rastreavel = EXCLUDED.rastreavel,
  arquivado = EXCLUDED.arquivado,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.products (
  id, hospital_id, nome, categoria, referencia, tecido, tamanhos, cores, dimensoes, detalhes, imagem_principal, imagens_detalhe, pintura, marca_cliente, nome_campo, timbrado, rastreavel, arquivado, created_at, updated_at
) VALUES (
  'f1000002-0000-4000-8000-000000000032',
  '56cd484d-914f-4d7d-9114-c8a51982e414',
  'Moletom G',
  'Moletom',
  'SB - 0032',
  'Moletom Flanelado',
  ARRAY['G']::text[],
  '[{"id":"c-azul","nome":"Azul","hex":"#223b7b"},{"id":"c-verde","nome":"Verde","hex":"#00683a"}]'::jsonb,
  '[{"id":"dim-32","titulo":"Dimensões","largura":"60 cm","altura":"72 cm","unidade":"cm"}]'::jsonb,
  '[{"id":"det-32","texto":"Punho e barra com ribana"}]'::jsonb,
  '',
  '[]'::jsonb,
  '{"cor":"","tamanho":"","localizacao":"","imagem":""}'::jsonb,
  '{"cor":"","tamanho":"","localizacao":"","imagem":""}'::jsonb,
  '{"texto":"","cor":"","tamanho":"","localizacao":""}'::jsonb,
  '{"ativo":false,"imagem":""}'::jsonb,
  '{"ativo":false,"imagem":""}'::jsonb,
  FALSE,
  now(),
  now()
) ON CONFLICT (id) DO UPDATE SET
  hospital_id = EXCLUDED.hospital_id,
  nome = EXCLUDED.nome,
  categoria = EXCLUDED.categoria,
  referencia = EXCLUDED.referencia,
  tecido = EXCLUDED.tecido,
  tamanhos = EXCLUDED.tamanhos,
  cores = EXCLUDED.cores,
  dimensoes = EXCLUDED.dimensoes,
  detalhes = EXCLUDED.detalhes,
  imagem_principal = EXCLUDED.imagem_principal,
  imagens_detalhe = EXCLUDED.imagens_detalhe,
  pintura = EXCLUDED.pintura,
  marca_cliente = EXCLUDED.marca_cliente,
  nome_campo = EXCLUDED.nome_campo,
  timbrado = EXCLUDED.timbrado,
  rastreavel = EXCLUDED.rastreavel,
  arquivado = EXCLUDED.arquivado,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.products (
  id, hospital_id, nome, categoria, referencia, tecido, tamanhos, cores, dimensoes, detalhes, imagem_principal, imagens_detalhe, pintura, marca_cliente, nome_campo, timbrado, rastreavel, arquivado, created_at, updated_at
) VALUES (
  'f1000003-0000-4000-8000-000000000033',
  '56cd484d-914f-4d7d-9114-c8a51982e414',
  'Moletom GG',
  'Moletom',
  'SB - 0033',
  'Moletom Flanelado',
  ARRAY['GG']::text[],
  '[{"id":"c-azul","nome":"Azul","hex":"#223b7b"},{"id":"c-verde","nome":"Verde","hex":"#00683a"}]'::jsonb,
  '[{"id":"dim-33","titulo":"Dimensões","largura":"64 cm","altura":"75 cm","unidade":"cm"}]'::jsonb,
  '[{"id":"det-33","texto":"Punho e barra com ribana"}]'::jsonb,
  '',
  '[]'::jsonb,
  '{"cor":"","tamanho":"","localizacao":"","imagem":""}'::jsonb,
  '{"cor":"","tamanho":"","localizacao":"","imagem":""}'::jsonb,
  '{"texto":"","cor":"","tamanho":"","localizacao":""}'::jsonb,
  '{"ativo":false,"imagem":""}'::jsonb,
  '{"ativo":false,"imagem":""}'::jsonb,
  FALSE,
  now(),
  now()
) ON CONFLICT (id) DO UPDATE SET
  hospital_id = EXCLUDED.hospital_id,
  nome = EXCLUDED.nome,
  categoria = EXCLUDED.categoria,
  referencia = EXCLUDED.referencia,
  tecido = EXCLUDED.tecido,
  tamanhos = EXCLUDED.tamanhos,
  cores = EXCLUDED.cores,
  dimensoes = EXCLUDED.dimensoes,
  detalhes = EXCLUDED.detalhes,
  imagem_principal = EXCLUDED.imagem_principal,
  imagens_detalhe = EXCLUDED.imagens_detalhe,
  pintura = EXCLUDED.pintura,
  marca_cliente = EXCLUDED.marca_cliente,
  nome_campo = EXCLUDED.nome_campo,
  timbrado = EXCLUDED.timbrado,
  rastreavel = EXCLUDED.rastreavel,
  arquivado = EXCLUDED.arquivado,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.products (
  id, hospital_id, nome, categoria, referencia, tecido, tamanhos, cores, dimensoes, detalhes, imagem_principal, imagens_detalhe, pintura, marca_cliente, nome_campo, timbrado, rastreavel, arquivado, created_at, updated_at
) VALUES (
  'f1000004-0000-4000-8000-000000000034',
  '56cd484d-914f-4d7d-9114-c8a51982e414',
  'Moletom EXG',
  'Moletom',
  'SB - 0034',
  'Moletom Flanelado',
  ARRAY['EXG']::text[],
  '[{"id":"c-azul","nome":"Azul","hex":"#223b7b"},{"id":"c-verde","nome":"Verde","hex":"#00683a"}]'::jsonb,
  '[{"id":"dim-34","titulo":"Dimensões","largura":"70 cm","altura":"80 cm","unidade":"cm"}]'::jsonb,
  '[{"id":"det-34","texto":"Punho e barra com ribana"}]'::jsonb,
  '',
  '[]'::jsonb,
  '{"cor":"","tamanho":"","localizacao":"","imagem":""}'::jsonb,
  '{"cor":"","tamanho":"","localizacao":"","imagem":""}'::jsonb,
  '{"texto":"","cor":"","tamanho":"","localizacao":""}'::jsonb,
  '{"ativo":false,"imagem":""}'::jsonb,
  '{"ativo":false,"imagem":""}'::jsonb,
  FALSE,
  now(),
  now()
) ON CONFLICT (id) DO UPDATE SET
  hospital_id = EXCLUDED.hospital_id,
  nome = EXCLUDED.nome,
  categoria = EXCLUDED.categoria,
  referencia = EXCLUDED.referencia,
  tecido = EXCLUDED.tecido,
  tamanhos = EXCLUDED.tamanhos,
  cores = EXCLUDED.cores,
  dimensoes = EXCLUDED.dimensoes,
  detalhes = EXCLUDED.detalhes,
  imagem_principal = EXCLUDED.imagem_principal,
  imagens_detalhe = EXCLUDED.imagens_detalhe,
  pintura = EXCLUDED.pintura,
  marca_cliente = EXCLUDED.marca_cliente,
  nome_campo = EXCLUDED.nome_campo,
  timbrado = EXCLUDED.timbrado,
  rastreavel = EXCLUDED.rastreavel,
  arquivado = EXCLUDED.arquivado,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.products (
  id, hospital_id, nome, categoria, referencia, tecido, tamanhos, cores, dimensoes, detalhes, imagem_principal, imagens_detalhe, pintura, marca_cliente, nome_campo, timbrado, rastreavel, arquivado, created_at, updated_at
) VALUES (
  'f1000005-0000-4000-8000-000000000035',
  '56cd484d-914f-4d7d-9114-c8a51982e414',
  'Avental cirúrgico sem opa',
  'Cirurgico',
  'SB - 0035',
  'Brim 100% algodão',
  ARRAY['UNICO']::text[],
  '[{"id":"c-azul","nome":"AZUL CELESTE (0003)","hex":"#8197cd"},{"id":"c-verde","nome":"VERDE AGUA (0002)","hex":"#96d2b2"}]'::jsonb,
  '[{"id":"dim-35","titulo":"Dimensões","largura":"80 cm","altura":"1,35 m","unidade":"cm"}]'::jsonb,
  '[{"id":"det-35","texto":"Sem opa, tiras de amarração traseiras e punho de ribana"}]'::jsonb,
  '',
  '[]'::jsonb,
  '{"cor":"","tamanho":"","localizacao":"","imagem":""}'::jsonb,
  '{"cor":"","tamanho":"","localizacao":"","imagem":""}'::jsonb,
  '{"texto":"","cor":"","tamanho":"","localizacao":""}'::jsonb,
  '{"ativo":false,"imagem":""}'::jsonb,
  '{"ativo":false,"imagem":""}'::jsonb,
  FALSE,
  now(),
  now()
) ON CONFLICT (id) DO UPDATE SET
  hospital_id = EXCLUDED.hospital_id,
  nome = EXCLUDED.nome,
  categoria = EXCLUDED.categoria,
  referencia = EXCLUDED.referencia,
  tecido = EXCLUDED.tecido,
  tamanhos = EXCLUDED.tamanhos,
  cores = EXCLUDED.cores,
  dimensoes = EXCLUDED.dimensoes,
  detalhes = EXCLUDED.detalhes,
  imagem_principal = EXCLUDED.imagem_principal,
  imagens_detalhe = EXCLUDED.imagens_detalhe,
  pintura = EXCLUDED.pintura,
  marca_cliente = EXCLUDED.marca_cliente,
  nome_campo = EXCLUDED.nome_campo,
  timbrado = EXCLUDED.timbrado,
  rastreavel = EXCLUDED.rastreavel,
  arquivado = EXCLUDED.arquivado,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.products (
  id, hospital_id, nome, categoria, referencia, tecido, tamanhos, cores, dimensoes, detalhes, imagem_principal, imagens_detalhe, pintura, marca_cliente, nome_campo, timbrado, rastreavel, arquivado, created_at, updated_at
) VALUES (
  'f1000006-0000-4000-8000-000000000036',
  '56cd484d-914f-4d7d-9114-c8a51982e414',
  'Campo Coronário',
  'Campo',
  'SB - 0036',
  'Brim 100% algodão',
  ARRAY['UNICO']::text[],
  '[{"id":"c-branco","nome":"BRANCO (0004)","hex":"#ffffff"}]'::jsonb,
  '[{"id":"dim-36","titulo":"Dimensões","largura":"75 cm","altura":"75 cm","unidade":"cm"}]'::jsonb,
  '[{"id":"det-36","texto":"Bainha de 1 cm em toda a borda"}]'::jsonb,
  '',
  '[]'::jsonb,
  '{"cor":"","tamanho":"","localizacao":"","imagem":""}'::jsonb,
  '{"cor":"","tamanho":"","localizacao":"","imagem":""}'::jsonb,
  '{"texto":"","cor":"","tamanho":"","localizacao":""}'::jsonb,
  '{"ativo":false,"imagem":""}'::jsonb,
  '{"ativo":false,"imagem":""}'::jsonb,
  FALSE,
  now(),
  now()
) ON CONFLICT (id) DO UPDATE SET
  hospital_id = EXCLUDED.hospital_id,
  nome = EXCLUDED.nome,
  categoria = EXCLUDED.categoria,
  referencia = EXCLUDED.referencia,
  tecido = EXCLUDED.tecido,
  tamanhos = EXCLUDED.tamanhos,
  cores = EXCLUDED.cores,
  dimensoes = EXCLUDED.dimensoes,
  detalhes = EXCLUDED.detalhes,
  imagem_principal = EXCLUDED.imagem_principal,
  imagens_detalhe = EXCLUDED.imagens_detalhe,
  pintura = EXCLUDED.pintura,
  marca_cliente = EXCLUDED.marca_cliente,
  nome_campo = EXCLUDED.nome_campo,
  timbrado = EXCLUDED.timbrado,
  rastreavel = EXCLUDED.rastreavel,
  arquivado = EXCLUDED.arquivado,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.products (
  id, hospital_id, nome, categoria, referencia, tecido, tamanhos, cores, dimensoes, detalhes, imagem_principal, imagens_detalhe, pintura, marca_cliente, nome_campo, timbrado, rastreavel, arquivado, created_at, updated_at
) VALUES (
  'f1000007-0000-4000-8000-000000000037',
  '56cd484d-914f-4d7d-9114-c8a51982e414',
  'Campo Fenestrado Duplo',
  'Campo',
  'SB - 0037',
  'Brim 100% algodão',
  ARRAY['UNICO']::text[],
  '[{"id":"c-verde","nome":"VERDE AGUA (0002)","hex":"#96d2b2"}]'::jsonb,
  '[{"id":"dim-37","titulo":"Dimensões","largura":"75 cm","altura":"75 cm","unidade":"cm"}]'::jsonb,
  '[{"id":"det-37","texto":"Camada dupla com fenestra central reforçada"}]'::jsonb,
  '',
  '[]'::jsonb,
  '{"cor":"","tamanho":"","localizacao":"","imagem":""}'::jsonb,
  '{"cor":"","tamanho":"","localizacao":"","imagem":""}'::jsonb,
  '{"texto":"","cor":"","tamanho":"","localizacao":""}'::jsonb,
  '{"ativo":false,"imagem":""}'::jsonb,
  '{"ativo":false,"imagem":""}'::jsonb,
  FALSE,
  now(),
  now()
) ON CONFLICT (id) DO UPDATE SET
  hospital_id = EXCLUDED.hospital_id,
  nome = EXCLUDED.nome,
  categoria = EXCLUDED.categoria,
  referencia = EXCLUDED.referencia,
  tecido = EXCLUDED.tecido,
  tamanhos = EXCLUDED.tamanhos,
  cores = EXCLUDED.cores,
  dimensoes = EXCLUDED.dimensoes,
  detalhes = EXCLUDED.detalhes,
  imagem_principal = EXCLUDED.imagem_principal,
  imagens_detalhe = EXCLUDED.imagens_detalhe,
  pintura = EXCLUDED.pintura,
  marca_cliente = EXCLUDED.marca_cliente,
  nome_campo = EXCLUDED.nome_campo,
  timbrado = EXCLUDED.timbrado,
  rastreavel = EXCLUDED.rastreavel,
  arquivado = EXCLUDED.arquivado,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.products (
  id, hospital_id, nome, categoria, referencia, tecido, tamanhos, cores, dimensoes, detalhes, imagem_principal, imagens_detalhe, pintura, marca_cliente, nome_campo, timbrado, rastreavel, arquivado, created_at, updated_at
) VALUES (
  'f1000008-0000-4000-8000-000000000038',
  '56cd484d-914f-4d7d-9114-c8a51982e414',
  'Camisola CC',
  'Camisola',
  'SB - 0038',
  'Algodão',
  ARRAY['UNICO']::text[],
  '[{"id":"c-azul","nome":"AZUL CELESTE (0003)","hex":"#8197cd"},{"id":"c-branco","nome":"BRANCO (0004)","hex":"#ffffff"},{"id":"c-verde","nome":"VERDE AGUA (0002)","hex":"#96d2b2"}]'::jsonb,
  '[{"id":"dim-38","titulo":"Dimensões","largura":"65 cm","altura":"1,00 m","unidade":"cm"}]'::jsonb,
  '[{"id":"det-38","texto":"Modelo para Centro Cirúrgico com amarração traseira"}]'::jsonb,
  '',
  '[]'::jsonb,
  '{"cor":"","tamanho":"","localizacao":"","imagem":""}'::jsonb,
  '{"cor":"","tamanho":"","localizacao":"","imagem":""}'::jsonb,
  '{"texto":"","cor":"","tamanho":"","localizacao":""}'::jsonb,
  '{"ativo":false,"imagem":""}'::jsonb,
  '{"ativo":false,"imagem":""}'::jsonb,
  FALSE,
  now(),
  now()
) ON CONFLICT (id) DO UPDATE SET
  hospital_id = EXCLUDED.hospital_id,
  nome = EXCLUDED.nome,
  categoria = EXCLUDED.categoria,
  referencia = EXCLUDED.referencia,
  tecido = EXCLUDED.tecido,
  tamanhos = EXCLUDED.tamanhos,
  cores = EXCLUDED.cores,
  dimensoes = EXCLUDED.dimensoes,
  detalhes = EXCLUDED.detalhes,
  imagem_principal = EXCLUDED.imagem_principal,
  imagens_detalhe = EXCLUDED.imagens_detalhe,
  pintura = EXCLUDED.pintura,
  marca_cliente = EXCLUDED.marca_cliente,
  nome_campo = EXCLUDED.nome_campo,
  timbrado = EXCLUDED.timbrado,
  rastreavel = EXCLUDED.rastreavel,
  arquivado = EXCLUDED.arquivado,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.products (
  id, hospital_id, nome, categoria, referencia, tecido, tamanhos, cores, dimensoes, detalhes, imagem_principal, imagens_detalhe, pintura, marca_cliente, nome_campo, timbrado, rastreavel, arquivado, created_at, updated_at
) VALUES (
  'f1000009-0000-4000-8000-000000000039',
  '56cd484d-914f-4d7d-9114-c8a51982e414',
  'Camisola Obeso',
  'Camisola',
  'SB - 0039',
  'Algodão',
  ARRAY['UNICO']::text[],
  '[{"id":"c-branco","nome":"BRANCO (0004)","hex":"#ffffff"}]'::jsonb,
  '[{"id":"dim-39","titulo":"Dimensões","largura":"1,30 m","altura":"1,20 m","unidade":"cm"}]'::jsonb,
  '[{"id":"det-39","texto":"Modelagem ampla especial para pacientes bariátricos/obesos"}]'::jsonb,
  '',
  '[]'::jsonb,
  '{"cor":"","tamanho":"","localizacao":"","imagem":""}'::jsonb,
  '{"cor":"","tamanho":"","localizacao":"","imagem":""}'::jsonb,
  '{"texto":"","cor":"","tamanho":"","localizacao":""}'::jsonb,
  '{"ativo":false,"imagem":""}'::jsonb,
  '{"ativo":false,"imagem":""}'::jsonb,
  FALSE,
  now(),
  now()
) ON CONFLICT (id) DO UPDATE SET
  hospital_id = EXCLUDED.hospital_id,
  nome = EXCLUDED.nome,
  categoria = EXCLUDED.categoria,
  referencia = EXCLUDED.referencia,
  tecido = EXCLUDED.tecido,
  tamanhos = EXCLUDED.tamanhos,
  cores = EXCLUDED.cores,
  dimensoes = EXCLUDED.dimensoes,
  detalhes = EXCLUDED.detalhes,
  imagem_principal = EXCLUDED.imagem_principal,
  imagens_detalhe = EXCLUDED.imagens_detalhe,
  pintura = EXCLUDED.pintura,
  marca_cliente = EXCLUDED.marca_cliente,
  nome_campo = EXCLUDED.nome_campo,
  timbrado = EXCLUDED.timbrado,
  rastreavel = EXCLUDED.rastreavel,
  arquivado = EXCLUDED.arquivado,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.products (
  id, hospital_id, nome, categoria, referencia, tecido, tamanhos, cores, dimensoes, detalhes, imagem_principal, imagens_detalhe, pintura, marca_cliente, nome_campo, timbrado, rastreavel, arquivado, created_at, updated_at
) VALUES (
  'f1000010-0000-4000-8000-000000000040',
  '56cd484d-914f-4d7d-9114-c8a51982e414',
  'Camisola Adulto Oxford',
  'Camisola',
  'SB - 0040',
  'Oxford 100% Poliester',
  ARRAY['UNICO']::text[],
  '[{"id":"c-azul","nome":"AZUL CELESTE (0003)","hex":"#8197cd"}]'::jsonb,
  '[{"id":"dim-40","titulo":"Dimensões","largura":"65 cm","altura":"1,05 m","unidade":"cm"}]'::jsonb,
  '[{"id":"det-40","texto":"Confeccionada em tecido Oxford resistente e de fácil higienização"}]'::jsonb,
  '',
  '[]'::jsonb,
  '{"cor":"","tamanho":"","localizacao":"","imagem":""}'::jsonb,
  '{"cor":"","tamanho":"","localizacao":"","imagem":""}'::jsonb,
  '{"texto":"","cor":"","tamanho":"","localizacao":""}'::jsonb,
  '{"ativo":false,"imagem":""}'::jsonb,
  '{"ativo":false,"imagem":""}'::jsonb,
  FALSE,
  now(),
  now()
) ON CONFLICT (id) DO UPDATE SET
  hospital_id = EXCLUDED.hospital_id,
  nome = EXCLUDED.nome,
  categoria = EXCLUDED.categoria,
  referencia = EXCLUDED.referencia,
  tecido = EXCLUDED.tecido,
  tamanhos = EXCLUDED.tamanhos,
  cores = EXCLUDED.cores,
  dimensoes = EXCLUDED.dimensoes,
  detalhes = EXCLUDED.detalhes,
  imagem_principal = EXCLUDED.imagem_principal,
  imagens_detalhe = EXCLUDED.imagens_detalhe,
  pintura = EXCLUDED.pintura,
  marca_cliente = EXCLUDED.marca_cliente,
  nome_campo = EXCLUDED.nome_campo,
  timbrado = EXCLUDED.timbrado,
  rastreavel = EXCLUDED.rastreavel,
  arquivado = EXCLUDED.arquivado,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.products (
  id, hospital_id, nome, categoria, referencia, tecido, tamanhos, cores, dimensoes, detalhes, imagem_principal, imagens_detalhe, pintura, marca_cliente, nome_campo, timbrado, rastreavel, arquivado, created_at, updated_at
) VALUES (
  'f1000011-0000-4000-8000-000000000041',
  '56cd484d-914f-4d7d-9114-c8a51982e414',
  'Camisola Tamanho Especial',
  'Camisola',
  'SB - 0041',
  'Algodão',
  ARRAY['ESPECIAL']::text[],
  '[{"id":"c-azul","nome":"AZUL CELESTE (0003)","hex":"#8197cd"}]'::jsonb,
  '[{"id":"dim-41","titulo":"Dimensões","largura":"1,20 m","altura":"1,15 m","unidade":"cm"}]'::jsonb,
  '[{"id":"det-41","texto":"Tamanho especial com amarração reforçada"}]'::jsonb,
  '',
  '[]'::jsonb,
  '{"cor":"","tamanho":"","localizacao":"","imagem":""}'::jsonb,
  '{"cor":"","tamanho":"","localizacao":"","imagem":""}'::jsonb,
  '{"texto":"","cor":"","tamanho":"","localizacao":""}'::jsonb,
  '{"ativo":false,"imagem":""}'::jsonb,
  '{"ativo":false,"imagem":""}'::jsonb,
  FALSE,
  now(),
  now()
) ON CONFLICT (id) DO UPDATE SET
  hospital_id = EXCLUDED.hospital_id,
  nome = EXCLUDED.nome,
  categoria = EXCLUDED.categoria,
  referencia = EXCLUDED.referencia,
  tecido = EXCLUDED.tecido,
  tamanhos = EXCLUDED.tamanhos,
  cores = EXCLUDED.cores,
  dimensoes = EXCLUDED.dimensoes,
  detalhes = EXCLUDED.detalhes,
  imagem_principal = EXCLUDED.imagem_principal,
  imagens_detalhe = EXCLUDED.imagens_detalhe,
  pintura = EXCLUDED.pintura,
  marca_cliente = EXCLUDED.marca_cliente,
  nome_campo = EXCLUDED.nome_campo,
  timbrado = EXCLUDED.timbrado,
  rastreavel = EXCLUDED.rastreavel,
  arquivado = EXCLUDED.arquivado,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.products (
  id, hospital_id, nome, categoria, referencia, tecido, tamanhos, cores, dimensoes, detalhes, imagem_principal, imagens_detalhe, pintura, marca_cliente, nome_campo, timbrado, rastreavel, arquivado, created_at, updated_at
) VALUES (
  'f1000012-0000-4000-8000-000000000042',
  '56cd484d-914f-4d7d-9114-c8a51982e414',
  'Calça Privativa PP',
  'Privativo',
  'SB - 0042',
  'Cedromix / Percal Misto',
  ARRAY['PP']::text[],
  '[{"id":"c-azul","nome":"AZUL CELESTE (0003)","hex":"#8197cd"},{"id":"c-verde","nome":"VERDE AGUA (0002)","hex":"#96d2b2"}]'::jsonb,
  '[{"id":"dim-42-1","titulo":"Cintura e Altura","largura":"28 cm / 45 cm","altura":"1,05 m","unidade":"cm"},{"id":"dim-42-2","titulo":"Bolso","largura":"14 cm","altura":"15 cm","unidade":"cm"},{"id":"dim-42-3","titulo":"Barra","largura":"20 cm","altura":"","unidade":"cm"}]'::jsonb,
  '[{"id":"det-42","texto":"Calça privativa com elástico na cintura e bolso"}]'::jsonb,
  '',
  '[]'::jsonb,
  '{"cor":"","tamanho":"","localizacao":"","imagem":""}'::jsonb,
  '{"cor":"","tamanho":"","localizacao":"","imagem":""}'::jsonb,
  '{"texto":"","cor":"","tamanho":"","localizacao":""}'::jsonb,
  '{"ativo":false,"imagem":""}'::jsonb,
  '{"ativo":false,"imagem":""}'::jsonb,
  FALSE,
  now(),
  now()
) ON CONFLICT (id) DO UPDATE SET
  hospital_id = EXCLUDED.hospital_id,
  nome = EXCLUDED.nome,
  categoria = EXCLUDED.categoria,
  referencia = EXCLUDED.referencia,
  tecido = EXCLUDED.tecido,
  tamanhos = EXCLUDED.tamanhos,
  cores = EXCLUDED.cores,
  dimensoes = EXCLUDED.dimensoes,
  detalhes = EXCLUDED.detalhes,
  imagem_principal = EXCLUDED.imagem_principal,
  imagens_detalhe = EXCLUDED.imagens_detalhe,
  pintura = EXCLUDED.pintura,
  marca_cliente = EXCLUDED.marca_cliente,
  nome_campo = EXCLUDED.nome_campo,
  timbrado = EXCLUDED.timbrado,
  rastreavel = EXCLUDED.rastreavel,
  arquivado = EXCLUDED.arquivado,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.products (
  id, hospital_id, nome, categoria, referencia, tecido, tamanhos, cores, dimensoes, detalhes, imagem_principal, imagens_detalhe, pintura, marca_cliente, nome_campo, timbrado, rastreavel, arquivado, created_at, updated_at
) VALUES (
  'f1000013-0000-4000-8000-000000000043',
  '56cd484d-914f-4d7d-9114-c8a51982e414',
  'Calça Privativa XG',
  'Privativo',
  'SB - 0043',
  'Cedromix / Percal Misto',
  ARRAY['XG']::text[],
  '[{"id":"c-azul","nome":"AZUL CELESTE (0003)","hex":"#8197cd"},{"id":"c-verde","nome":"VERDE AGUA (0002)","hex":"#96d2b2"}]'::jsonb,
  '[{"id":"dim-43-1","titulo":"Cintura e Altura","largura":"40 cm / 65 cm","altura":"1,18 m","unidade":"cm"},{"id":"dim-43-2","titulo":"Bolso","largura":"17 cm","altura":"17,5 cm","unidade":"cm"},{"id":"dim-43-3","titulo":"Barra","largura":"24 cm","altura":"","unidade":"cm"}]'::jsonb,
  '[{"id":"det-43","texto":"Calça privativa com elástico na cintura e bolso"}]'::jsonb,
  '',
  '[]'::jsonb,
  '{"cor":"","tamanho":"","localizacao":"","imagem":""}'::jsonb,
  '{"cor":"","tamanho":"","localizacao":"","imagem":""}'::jsonb,
  '{"texto":"","cor":"","tamanho":"","localizacao":""}'::jsonb,
  '{"ativo":false,"imagem":""}'::jsonb,
  '{"ativo":false,"imagem":""}'::jsonb,
  FALSE,
  now(),
  now()
) ON CONFLICT (id) DO UPDATE SET
  hospital_id = EXCLUDED.hospital_id,
  nome = EXCLUDED.nome,
  categoria = EXCLUDED.categoria,
  referencia = EXCLUDED.referencia,
  tecido = EXCLUDED.tecido,
  tamanhos = EXCLUDED.tamanhos,
  cores = EXCLUDED.cores,
  dimensoes = EXCLUDED.dimensoes,
  detalhes = EXCLUDED.detalhes,
  imagem_principal = EXCLUDED.imagem_principal,
  imagens_detalhe = EXCLUDED.imagens_detalhe,
  pintura = EXCLUDED.pintura,
  marca_cliente = EXCLUDED.marca_cliente,
  nome_campo = EXCLUDED.nome_campo,
  timbrado = EXCLUDED.timbrado,
  rastreavel = EXCLUDED.rastreavel,
  arquivado = EXCLUDED.arquivado,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.products (
  id, hospital_id, nome, categoria, referencia, tecido, tamanhos, cores, dimensoes, detalhes, imagem_principal, imagens_detalhe, pintura, marca_cliente, nome_campo, timbrado, rastreavel, arquivado, created_at, updated_at
) VALUES (
  'f1000014-0000-4000-8000-000000000044',
  '56cd484d-914f-4d7d-9114-c8a51982e414',
  'Camisa Privativa PP',
  'Privativo',
  'SB - 0044',
  'Cedromix / Percal Misto',
  ARRAY['PP']::text[],
  '[{"id":"c-azul","nome":"AZUL CELESTE (0003)","hex":"#8197cd"},{"id":"c-verde","nome":"VERDE AGUA (0002)","hex":"#96d2b2"}]'::jsonb,
  '[{"id":"dim-44","titulo":"Dimensões","largura":"55 cm","altura":"60 cm","unidade":"cm"}]'::jsonb,
  '[{"id":"det-44","texto":"Gola V com bolso superior e bolsos inferiores"}]'::jsonb,
  '',
  '[]'::jsonb,
  '{"cor":"","tamanho":"","localizacao":"","imagem":""}'::jsonb,
  '{"cor":"","tamanho":"","localizacao":"","imagem":""}'::jsonb,
  '{"texto":"","cor":"","tamanho":"","localizacao":""}'::jsonb,
  '{"ativo":false,"imagem":""}'::jsonb,
  '{"ativo":false,"imagem":""}'::jsonb,
  FALSE,
  now(),
  now()
) ON CONFLICT (id) DO UPDATE SET
  hospital_id = EXCLUDED.hospital_id,
  nome = EXCLUDED.nome,
  categoria = EXCLUDED.categoria,
  referencia = EXCLUDED.referencia,
  tecido = EXCLUDED.tecido,
  tamanhos = EXCLUDED.tamanhos,
  cores = EXCLUDED.cores,
  dimensoes = EXCLUDED.dimensoes,
  detalhes = EXCLUDED.detalhes,
  imagem_principal = EXCLUDED.imagem_principal,
  imagens_detalhe = EXCLUDED.imagens_detalhe,
  pintura = EXCLUDED.pintura,
  marca_cliente = EXCLUDED.marca_cliente,
  nome_campo = EXCLUDED.nome_campo,
  timbrado = EXCLUDED.timbrado,
  rastreavel = EXCLUDED.rastreavel,
  arquivado = EXCLUDED.arquivado,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.products (
  id, hospital_id, nome, categoria, referencia, tecido, tamanhos, cores, dimensoes, detalhes, imagem_principal, imagens_detalhe, pintura, marca_cliente, nome_campo, timbrado, rastreavel, arquivado, created_at, updated_at
) VALUES (
  'f1000015-0000-4000-8000-000000000045',
  '56cd484d-914f-4d7d-9114-c8a51982e414',
  'Camisa Privativa XG',
  'Privativo',
  'SB - 0045',
  'Cedromix / Percal Misto',
  ARRAY['XG']::text[],
  '[{"id":"c-azul","nome":"AZUL CELESTE (0003)","hex":"#8197cd"},{"id":"c-verde","nome":"VERDE AGUA (0002)","hex":"#96d2b2"}]'::jsonb,
  '[{"id":"dim-45","titulo":"Dimensões","largura":"78 cm","altura":"85 cm","unidade":"cm"}]'::jsonb,
  '[{"id":"det-45","texto":"Gola V com bolso superior e bolsos inferiores"}]'::jsonb,
  '',
  '[]'::jsonb,
  '{"cor":"","tamanho":"","localizacao":"","imagem":""}'::jsonb,
  '{"cor":"","tamanho":"","localizacao":"","imagem":""}'::jsonb,
  '{"texto":"","cor":"","tamanho":"","localizacao":""}'::jsonb,
  '{"ativo":false,"imagem":""}'::jsonb,
  '{"ativo":false,"imagem":""}'::jsonb,
  FALSE,
  now(),
  now()
) ON CONFLICT (id) DO UPDATE SET
  hospital_id = EXCLUDED.hospital_id,
  nome = EXCLUDED.nome,
  categoria = EXCLUDED.categoria,
  referencia = EXCLUDED.referencia,
  tecido = EXCLUDED.tecido,
  tamanhos = EXCLUDED.tamanhos,
  cores = EXCLUDED.cores,
  dimensoes = EXCLUDED.dimensoes,
  detalhes = EXCLUDED.detalhes,
  imagem_principal = EXCLUDED.imagem_principal,
  imagens_detalhe = EXCLUDED.imagens_detalhe,
  pintura = EXCLUDED.pintura,
  marca_cliente = EXCLUDED.marca_cliente,
  nome_campo = EXCLUDED.nome_campo,
  timbrado = EXCLUDED.timbrado,
  rastreavel = EXCLUDED.rastreavel,
  arquivado = EXCLUDED.arquivado,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.products (
  id, hospital_id, nome, categoria, referencia, tecido, tamanhos, cores, dimensoes, detalhes, imagem_principal, imagens_detalhe, pintura, marca_cliente, nome_campo, timbrado, rastreavel, arquivado, created_at, updated_at
) VALUES (
  'f1000016-0000-4000-8000-000000000046',
  '56cd484d-914f-4d7d-9114-c8a51982e414',
  'Fronha (Percal Misto)',
  'Fronha',
  'SB - 0046',
  'Percal Misto 60%alg. 40 % Poliéster',
  ARRAY['UNICO']::text[],
  '[{"id":"c-branco","nome":"BRANCO (0004)","hex":"#ffffff"}]'::jsonb,
  '[{"id":"dim-46","titulo":"Dimensões","largura":"70 cm","altura":"50 cm","unidade":"cm"}]'::jsonb,
  '[{"id":"det-46","texto":"Fronha hospitalar com transpasse / aba interna de 20 cm"}]'::jsonb,
  '',
  '[]'::jsonb,
  '{"cor":"","tamanho":"","localizacao":"","imagem":""}'::jsonb,
  '{"cor":"","tamanho":"","localizacao":"","imagem":""}'::jsonb,
  '{"texto":"","cor":"","tamanho":"","localizacao":""}'::jsonb,
  '{"ativo":false,"imagem":""}'::jsonb,
  '{"ativo":false,"imagem":""}'::jsonb,
  FALSE,
  now(),
  now()
) ON CONFLICT (id) DO UPDATE SET
  hospital_id = EXCLUDED.hospital_id,
  nome = EXCLUDED.nome,
  categoria = EXCLUDED.categoria,
  referencia = EXCLUDED.referencia,
  tecido = EXCLUDED.tecido,
  tamanhos = EXCLUDED.tamanhos,
  cores = EXCLUDED.cores,
  dimensoes = EXCLUDED.dimensoes,
  detalhes = EXCLUDED.detalhes,
  imagem_principal = EXCLUDED.imagem_principal,
  imagens_detalhe = EXCLUDED.imagens_detalhe,
  pintura = EXCLUDED.pintura,
  marca_cliente = EXCLUDED.marca_cliente,
  nome_campo = EXCLUDED.nome_campo,
  timbrado = EXCLUDED.timbrado,
  rastreavel = EXCLUDED.rastreavel,
  arquivado = EXCLUDED.arquivado,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.products (
  id, hospital_id, nome, categoria, referencia, tecido, tamanhos, cores, dimensoes, detalhes, imagem_principal, imagens_detalhe, pintura, marca_cliente, nome_campo, timbrado, rastreavel, arquivado, created_at, updated_at
) VALUES (
  'f1000017-0000-4000-8000-000000000047',
  '56cd484d-914f-4d7d-9114-c8a51982e414',
  'Lençol Vira Infantil (Percal Misto)',
  'Lençol',
  'SB - 0047',
  'Percal Misto 60%alg. 40 % Poliéster',
  ARRAY['UNICO']::text[],
  '[{"id":"c-branco","nome":"BRANCO (0004)","hex":"#ffffff"}]'::jsonb,
  '[{"id":"dim-47","titulo":"Dimensões","largura":"1,70 m","altura":"1,25 m","unidade":"m"}]'::jsonb,
  '[{"id":"det-47","texto":"Bainha de 1 cm em toda a volta"}]'::jsonb,
  '',
  '[]'::jsonb,
  '{"cor":"","tamanho":"","localizacao":"","imagem":""}'::jsonb,
  '{"cor":"","tamanho":"","localizacao":"","imagem":""}'::jsonb,
  '{"texto":"","cor":"","tamanho":"","localizacao":""}'::jsonb,
  '{"ativo":false,"imagem":""}'::jsonb,
  '{"ativo":false,"imagem":""}'::jsonb,
  FALSE,
  now(),
  now()
) ON CONFLICT (id) DO UPDATE SET
  hospital_id = EXCLUDED.hospital_id,
  nome = EXCLUDED.nome,
  categoria = EXCLUDED.categoria,
  referencia = EXCLUDED.referencia,
  tecido = EXCLUDED.tecido,
  tamanhos = EXCLUDED.tamanhos,
  cores = EXCLUDED.cores,
  dimensoes = EXCLUDED.dimensoes,
  detalhes = EXCLUDED.detalhes,
  imagem_principal = EXCLUDED.imagem_principal,
  imagens_detalhe = EXCLUDED.imagens_detalhe,
  pintura = EXCLUDED.pintura,
  marca_cliente = EXCLUDED.marca_cliente,
  nome_campo = EXCLUDED.nome_campo,
  timbrado = EXCLUDED.timbrado,
  rastreavel = EXCLUDED.rastreavel,
  arquivado = EXCLUDED.arquivado,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.products (
  id, hospital_id, nome, categoria, referencia, tecido, tamanhos, cores, dimensoes, detalhes, imagem_principal, imagens_detalhe, pintura, marca_cliente, nome_campo, timbrado, rastreavel, arquivado, created_at, updated_at
) VALUES (
  'f1000018-0000-4000-8000-000000000048',
  '56cd484d-914f-4d7d-9114-c8a51982e414',
  'Lençol Maca (Percal Misto)',
  'Lençol',
  'SB - 0048',
  'Percal Misto 60%alg. 40 % Poliéster',
  ARRAY['UNICO']::text[],
  '[{"id":"c-branco","nome":"BRANCO (0004)","hex":"#ffffff"}]'::jsonb,
  '[{"id":"dim-48","titulo":"Dimensões","largura":"2,20 m","altura":"80 cm","unidade":"cm"}]'::jsonb,
  '[{"id":"det-48","texto":"Bainha reforçada de 1 cm"}]'::jsonb,
  '',
  '[]'::jsonb,
  '{"cor":"","tamanho":"","localizacao":"","imagem":""}'::jsonb,
  '{"cor":"","tamanho":"","localizacao":"","imagem":""}'::jsonb,
  '{"texto":"","cor":"","tamanho":"","localizacao":""}'::jsonb,
  '{"ativo":false,"imagem":""}'::jsonb,
  '{"ativo":false,"imagem":""}'::jsonb,
  FALSE,
  now(),
  now()
) ON CONFLICT (id) DO UPDATE SET
  hospital_id = EXCLUDED.hospital_id,
  nome = EXCLUDED.nome,
  categoria = EXCLUDED.categoria,
  referencia = EXCLUDED.referencia,
  tecido = EXCLUDED.tecido,
  tamanhos = EXCLUDED.tamanhos,
  cores = EXCLUDED.cores,
  dimensoes = EXCLUDED.dimensoes,
  detalhes = EXCLUDED.detalhes,
  imagem_principal = EXCLUDED.imagem_principal,
  imagens_detalhe = EXCLUDED.imagens_detalhe,
  pintura = EXCLUDED.pintura,
  marca_cliente = EXCLUDED.marca_cliente,
  nome_campo = EXCLUDED.nome_campo,
  timbrado = EXCLUDED.timbrado,
  rastreavel = EXCLUDED.rastreavel,
  arquivado = EXCLUDED.arquivado,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.products (
  id, hospital_id, nome, categoria, referencia, tecido, tamanhos, cores, dimensoes, detalhes, imagem_principal, imagens_detalhe, pintura, marca_cliente, nome_campo, timbrado, rastreavel, arquivado, created_at, updated_at
) VALUES (
  'f1000019-0000-4000-8000-000000000049',
  '56cd484d-914f-4d7d-9114-c8a51982e414',
  'Lençol Vira (Percal Misto)',
  'Lençol',
  'SB - 0049',
  'Percal Misto 60%alg. 40 % Poliéster',
  ARRAY['UNICO']::text[],
  '[{"id":"c-branco","nome":"BRANCO (0004)","hex":"#ffffff"}]'::jsonb,
  '[{"id":"dim-49","titulo":"Dimensões","largura":"2,50 m","altura":"1,60 m","unidade":"m"}]'::jsonb,
  '[{"id":"det-49","texto":"Bainha dupla na vira"}]'::jsonb,
  '',
  '[]'::jsonb,
  '{"cor":"","tamanho":"","localizacao":"","imagem":""}'::jsonb,
  '{"cor":"","tamanho":"","localizacao":"","imagem":""}'::jsonb,
  '{"texto":"","cor":"","tamanho":"","localizacao":""}'::jsonb,
  '{"ativo":false,"imagem":""}'::jsonb,
  '{"ativo":false,"imagem":""}'::jsonb,
  FALSE,
  now(),
  now()
) ON CONFLICT (id) DO UPDATE SET
  hospital_id = EXCLUDED.hospital_id,
  nome = EXCLUDED.nome,
  categoria = EXCLUDED.categoria,
  referencia = EXCLUDED.referencia,
  tecido = EXCLUDED.tecido,
  tamanhos = EXCLUDED.tamanhos,
  cores = EXCLUDED.cores,
  dimensoes = EXCLUDED.dimensoes,
  detalhes = EXCLUDED.detalhes,
  imagem_principal = EXCLUDED.imagem_principal,
  imagens_detalhe = EXCLUDED.imagens_detalhe,
  pintura = EXCLUDED.pintura,
  marca_cliente = EXCLUDED.marca_cliente,
  nome_campo = EXCLUDED.nome_campo,
  timbrado = EXCLUDED.timbrado,
  rastreavel = EXCLUDED.rastreavel,
  arquivado = EXCLUDED.arquivado,
  updated_at = EXCLUDED.updated_at;

COMMIT;
